kind: Service                             
apiVersion: v1
metadata:
  name: css-website
  labels:
    app: css-website
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: css-website                  
  type: LoadBalancer            
