version: 2.1

jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
         fingerprints:
           - "1c:4a:4f:dd:26:3b:36:fd:6c:32:5a:59:6e:6e:8f:47"
           - "69:fd:0b:4e:14:73:d9:19:0a:96:05:f1:8c:99:52:83"

      - run:
          name: send Dockerfile to ansible server
          command: rsync -ravz --delete /home/circleci/project/* ubuntu@43.204.102.19:.
          
      - run: 
          name: "build Docker image"
          command: ssh -o StrictHostKeyChecking=no ubuntu@43.204.102.19 sudo docker build -t css-web-app:${CIRCLE_BUILD_NUM} .
             
      - run:
          name: "Tag docker images"
          command: ssh -o StrictHostKeyChecking=no ubuntu@43.204.102.19  sudo docker image tag css-web-app:${CIRCLE_BUILD_NUM}  mursalindocker111/css-web-app:${CIRCLE_BUILD_NUM};
                   ssh -o StrictHostKeyChecking=no ubuntu@43.204.102.19  sudo docker image tag css-web-app:${CIRCLE_BUILD_NUM}  mursalindocker111/css-web-app:V1.${CIRCLE_BUILD_NUM};           

      - run:
          name: "push docker image to docker hub"
          command: ssh -o StrictHostKeyChecking=no ubuntu@43.204.102.19 sudo docker login -u mursalindocker111 -p ${dockerhub_passwd};
                   ssh -o StrictHostKeyChecking=no ubuntu@43.204.102.19 sudo docker push mursalindocker111/css-web-app:${CIRCLE_BUILD_NUM};       
                   ssh -o StrictHostKeyChecking=no ubuntu@43.204.102.19 sudo docker push mursalindocker111/css-web-app:V1.${CIRCLE_BUILD_NUM};              
      - run: 
           name: "push file to Kmaster server"
           command:  rsync -ravz --delete /home/circleci/project/Deployment.yml Service.yml ubuntu@13.234.122.79:.
      


      # - run:
      #     name: Tag docker image
      #     command: ssh -o StrictHostKeyChecking=no ubuntu@15.207.89.114 sudo docker image tag nginx:latest  mursalindocker111/nginx:v1.${CIRCLE_BUILD_NUM};
      #              ssh -o StrictHostKeyChecking=no ubuntu@15.207.89.114 sudo docker image tag nginx:latest  mursalindocker111/nginx:latest;   
      # - run:
      #      name: push docker images to ansible server
      #      command:   ssh -o StrictHostKeyChecking=no ubuntu@15.207.89.114 sudo docker login --username mursalindocker111 --password $DOCKERHUB_PASSWORD;
      #                 ssh -o StrictHostKeyChecking=no ubuntu@15.207.89.114  sudo docker  push mursalindocker111/nginx:v1.${CIRCLE_BUILD_NUM};
      #                 ssh -o StrictHostKeyChecking=no ubuntu@15.207.89.114  sudo docker push mursalindocker111/nginx:latest;

workflows:
      sample:
        jobs:
           - deploy
