version: 2.1

jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "1c:4a:4f:dd:26:3b:36:fd:6c:32:5a:59:6e:6e:8f:47"

      - run:
          name: send dockerfilr to ansible server
          command: rsync -ravz --delete /home/circleci/project/* ubuntu@172.31.13.103:.      



      # - run:
      #     name: Tag docker image
      #     command: ssh -o StrictHostKeyChecking=no ubuntu@15.207.89.114 sudo docker image tag nginx:latest  mursalindocker111/nginx:v1.${CIRCLE_BUILD_NUM};
      #              ssh -o StrictHostKeyChecking=no ubuntu@15.207.89.114 sudo docker image tag nginx:latest  mursalindocker111/nginx:latest;   
      # - run:
      #      name: push docker images to ansible server
      #      command:   ssh -o StrictHostKeyChecking=no ubuntu@15.207.89.114 sudo docker login --username mursalindocker111 --password $DOCKERHUB_PASSWORD;
      #                 ssh -o StrictHostKeyChecking=no ubuntu@15.207.89.114  sudo docker  push mursalindocker111/nginx:v1.${CIRCLE_BUILD_NUM};
      #                 ssh -o StrictHostKeyChecking=no ubuntu@15.207.89.114  sudo docker push mursalindocker111/nginx:latest;

workflows:
      sample:
        jobs:
           - deploy
